steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args: ['--destination=gcr.io/$PROJECT_ID/onetrill', '--cache=true']
images:
- 'gcr.io/$PROJECT_ID/onetrill'
logsBucket: 'gs://codehub-cloudbuild-logs'